// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto_Carros;

namespace Projeto_Carros.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Projeto_Carros.Models.Carros", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Dt_Inc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Dt_Venda")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("Carros");
                });

            modelBuilder.Entity("Projeto_Carros.Models.Revisoes", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarrosCodigo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Dt_Inc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Dt_Revisao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Oficina")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<decimal?>("Valor")
                        .HasColumnType("decimal(9,3)");

                    b.HasKey("Codigo");

                    b.HasIndex("CarrosCodigo");

                    b.ToTable("Revisoes");
                });

            modelBuilder.Entity("Projeto_Carros.Models.Revisoes", b =>
                {
                    b.HasOne("Projeto_Carros.Models.Carros", "Carros")
                        .WithMany("Revisoes")
                        .HasForeignKey("CarrosCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
